#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

ini_set('memory_limit', '512M');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));
// Composer
require(__DIR__ . '/vendor/autoload.php');
// Environment
require(__DIR__ . '/config/env.php');

defined('YII_DEBUG') or define('YII_DEBUG', (boolean)env('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', env('YII_ENV'));

// Yii
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

// Bootstrap Application
require(__DIR__ . '/config/console/bootstrap.php');

$config = \yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/base.php'),
    require(__DIR__ . '/config/console/config.php')
);
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);